package Models.Networking;

public enum RequestType {
    SignUp,
    Login,
    TimeLine,
    SendTweet,
    Mute,
    Block,
    SendRetweet,
    LikeTweet,
    Comments,
    SendComment,
    Discovery,
    Profile,
    Follow,
    ListsList,
    AddList,
    List,
    Followings,
    AddUserToList,
    DeleteList,
    SelfProfile,
    ConversationList,
    Conversation,
    GroupMessageList,
    SendGroupMessage,
    SendMessageToConversation,
    SendMessageToUser,
    Test,
    Test2,
    Ping,
    HyperLink,
    AddMemberToGroup,
    LeaveGroup,
    CreateGroup,
    BlackList,
    UnBlock,
    ChangePrivacy,
    Privacy,
    EditProfileInfo,
    EditProfile,
    DeleteAccount,
    Notifications,
    AcceptRequest,
    DenyRequest,
    FollowRequests, DeleteMessage, EditMessage, Online, SendTweetGroupMessage, ReportTweet,

}
